#!/bin/bash

# Kopieert certs van certpath naar de cacert store van alle OpenJDK installaties.

JAVA_DIR_START=/opt/homebrew/opt
JAVA_DIR_REST=/libexec/openjdk.jdk/Contents/Home
certpath=~/Library/Certificates

for javadir in $(find $JAVA_DIR_START -name "openjdk@*" -type l); do
    echo "$javadir"

    for cert in "$certpath"/*
    do
        sudo $javadir$JAVA_DIR_REST/bin/keytool -import \
             -trustcacerts -cacerts \
             -storepass changeit -noprompt -alias $(basename $cert) \
             -file "$cert"
    done
done
