#!/bin/sh
pipe=/tmp/monsterbar
if [[ ! -p $pipe ]]; then
    mkfifo $pipe
fi

tags[0]='een'
tags[1]='twee'
tags[2]='drie'
tags[3]='vier'
tags[4]='vijf'
tags[5]='zes'
tags[6]='zeven'
tags[7]='acht'
tags[8]='negen'
tags[9]='tien'
#layouts=('[]=' '[ ]' 'TTT' '[#]')

printBar(){
    unset bar
    IFS=' '
    read -ra desktops <<"$1"
    desktops=($1)
    [[ "${desktops[@]}" =~ ^(([[:digit:]]+:)+[[:digit:]]+ ?)+$ ]] || return

    for desktop in "${desktops[@]}"
    do
        IFS=':' read -r d w m c u <<< "$desktop"
        label="${tags[$d]}"
    
        # Current open desktop? Change fg
        ((c)) && fg="&6" before="[" after="]" || fg="&1" before=" " after=" "

        bar+="$fg$before$label$after "
    done

    echo "$bar&C&1$(date)"
}

updateOnWM(){
    while true
    do
        inotifywait $pipe -e modify > /dev/null 2> /dev/null # Wait *silently* until file changes
        printBar "$(tail -1 /tmp/monsterbar)"
    done
}

updateOnSecond(){
    while true
    do
        printBar "$(tail -1 /tmp/monsterbar)"
        sleep 1
    done
}

updateOnSecond &
updateOnWM
