#!/bin/bash
pipe=/tmp/monsterbar
if [[ ! -p $pipe ]]; then
    mkfifo $pipe
fi

printBar(){
    echo "$1 &C $(date)"
}

updateOnWM(){
    while true
    do
        inotifywait $pipe -e modify
        printBar "$(tail -1 /tmp/monsterbar)"
    done
}

updateOnSecond(){
    while true
    do
        printBar "$(tail -1 /tmp/monsterbar)"
        sleep 1
    done
}

updateOnSecond &
updateOnWM
