export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=10000
shopt -s histappend
shopt -s cmdhist
shopt -u huponexit
shopt -s autocd

# Auto-complete command from history
export INPUTRC=~/.inputrc
export EDITOR="vi"

if [ -d "$HOME/scripts" ] ; then
    PATH="$HOME/scripts:$PATH"
fi

if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

PS1="; "

alias grep='grep --color=auto'
alias du='du -sh' # Only show the total in human readable format
alias df='df -h' # Show in human readable format
alias gits='git status'
alias gitc='git commit'
alias gitp='git push'
alias gita='git add'
alias gitd='git diff'
alias gitl='git log'

if [ "$(command -v nvim)" != '' ]; then
    alias v="nvim -p"
    alias vi="nvim -p"
    alias vim="nvim -p"
    export EDITOR="nvim -p"
fi

platform='unknown'
unamestr=$(uname)
if [ "$unamestr" = 'Linux' ]; then
    platform='linux'
elif [ "$unamestr" = 'FreeBSD' ]; then
    platform='freebsd'
fi

if [ "$platform" = 'linux' ]; then

    alias ls='ls -Glashop --color=auto --group-directories-first'

elif [ "$platform" = 'freebsd' ]; then

    alias ls='ls -G'

fi
